### ISSUE TITLE
Beispiel Vorlage

### ISSUE THREAD

**Issue by kelke** [dmke/thesis-template#11]
Wäre es möglich ein Beispiel-PDF in die Readme zu verlinken, an dem man sieht, wie die Vorlage aussieht ohne ruby und die repo runterladen zu müssen? :)

**Comment by dmke** [comment]
Ich glaube nicht, dass die Vorlage in ihrer aktuellen Form noch funktioniert; die wurde mal geschrieben, als Ruby 1.9 und TeX Live 2009 neu waren, das ist nun mehr als 10 Jahre her.

Ruby selber ist weniger ein Problem, als dass der Code im Wesentlichen eine Erweiterung von Rake ist - und dessen Code hat sich naturgemäß weiterentwickelt. Die Entwicklung der bei TeX-Klassen und -Bibliotheken habe ich nicht weiter verfolgt. `biber` war damals recht neu und wird von dieser Vorlage vorausgesetzt. Keine Ahnung, ob das noch dem aktuellen Stand entspricht...

Wenn du einen erfolgreichen Durchlauf geschafft hast, kannst du damit gerne einen PR erstellen :)

**Comment by kelke** [comment]
Ach so okay, das ist gut zu wissen. Vielen Dank für die schnelle und umfangreiche Antwort!

**Comment by dmke** [comment]
Kein Problem!

FWIW, ich würde komplexere Dokumente heute mit [`latexmk`](https://ctan.org/pkg/latexmk/) bauen. Das nimmt dir den automatischen Aufruf von pdf/xe/lualatex und biber/bibtex in der richtigen Reihenfolge und Anzahl ab.
