### ISSUE TITLE
Inkscape does not like relative pathes (macOS)

### ISSUE THREAD

**Issue by Dyddye** [dmke/thesis-template#8]
The conversion of a svg file fails, because relative pathes are not supported by Inkscape 0.92 (macOS).

Hotfix: latex.rb:51
```puts green('OK.') if sh "inkscape -f #{file} -A #{file.gsub /svg$/, "pdf"} >#{NULL_DEVICE}"```
turn into
```puts green('OK.') if sh "inkscape -f `pwd`/#{file} -A `pwd`/#{file.gsub /svg$/, "pdf"} >#{NULL_DEVICE}"```

**Comment by dmke** [comment]
That's an interesting construct:

```ruby
sh "... `pwd`/#{file}"
```

I've taken a slightliy different route :-)

**Comment by dmke** [comment]
Closed by #9
